language:
    - cpp

dist: xenial

install:
    - ls -alF
    - sudo apt-get install gcc-aarch64-linux-gnu
    - sudo apt-get install g++-aarch64-linux-gnu
    - aarch64-linux-gnu-gcc -v
    - aarch64-linux-gnu-g++ -v
    - sudo pip install lizard

script: 
    - make clean	
    - make
    - ./ascend
    - lizard
    - mkdir res
    - lizard --xml > result.xml
    - python abc.py